
meta_product_name: "SmartFoods"
meta_title: "SmartFoods - Reach your goals"
meta_description: "SmartFoods breaks down the foods that will help you reach your goals in a simple and digestible way. Get access to hundreds of recipes and order a food pickup at your local grocery shop."
meta_image: "acre.png" # should exist in `app/assets/images/`
